<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script>
Promise.resolve()
  .then( () => {
    // 使 .then() 返回一个 rejected promise
    // throw 'Oh no!';
    throw '123'
  })
  .catch( reason => {
    console.error( 'onRejected function called: ', reason );
  })
  .then( () => {
    console.log( "I am always called even if the prior then's promise rejects" );
  }).then(() => {
      console.log('123')
  });
    </script>
</body>
</html>